# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Updates fastlane if needed
update_fastlane

default_platform(:ios)

platform :ios do

  desc "Test the Swift Package Manager"
  lane :test do
    
    UI.header("Run tests script")
    sh "cd .. && rm -rf .build"
    sh "python3 ../tests/tests.py"

  end

end
